# auto: true

markdown: kramdown
highlighter: rouge
paginate: 8
permalink: /:title
encoding: UTF-8
gems: [jekyll-paginate]

title: Github Blog JunWeiUp
url: http://JunWeiUp.github.io
feed: /atom.xml
author_info: <a href="http://JunWeiUp.github.io/">JunWeiUp</a>

myblog:
  gavatar: images/2.jpg
  gpname: JunWeiUp
  linkedin: http://weibo.com/JunWeiUp
  github: https://github.com/JunWeiUp
  email:  mailto:junweiup@gmail.com
  coverimgs: []
  postbgimg: []

categories: [python, books]
