# auto: true

markdown: kramdown
highlighter: rouge
paginate: 8
permalink: /:title
encoding: UTF-8
gems: [jekyll-paginate]

title: Github Blog Template
url: http://litaotao.github.io
feed: /atom.xml
author_info: <a href="http://litaotao.github.io/">taotaoli</a>

myblog:
  gavatar: images/3.jpg
  gpname: JunWeiUp
  linkedin: http://weibo.com/JunWeiUp
  github: https://github.com/JunWeiUp
  email: junweiup@gmail.com
  coverimgs: []
  postbgimg: []

categories: [python, books]
